export const dummyPost = [
  {
    postNo: 1,
    postTitle: "제목 1",
    postAuthor: "글쓴이1",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 2,
    postTitle: "제목 2",
    postAuthor: "글쓴이2",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 3,
    postTitle: "제목 3",
    postAuthor: "글쓴이3",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 4,
    postTitle: "제목 4",
    postAuthor: "글쓴이4",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 5,
    postTitle: "제목 5",
    postAuthor: "글쓴이5",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 6,
    postTitle: "제목 6입니다~~~~~~~~~~~~~",
    postAuthor: "글쓴이666666666",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 7,
    postTitle: "제목 7입니다~~~~~~~~~~~~~",
    postAuthor: "글쓴이77",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 8,
    postTitle: "제목 7입니다~~~~~~~~~~~~~",
    postAuthor: "글쓴이77",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 9,
    postTitle: "제목 9입@@@@@@@@@니다~~~~~~~~~~~~~",
    postAuthor: "글쓴이9",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
  {
    postNo: 10,
    postTitle: "제목 10입니다~~~~~~@@@@@@@@@~~~~~~~",
    postAuthor: "글쓴이101010",
    postCreateDate: "2022/9/21",
    postLikes: 0,
    postViews: 0,
  },
];
